import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# Plots the charm->D0 LHAPDF fragmentation function D(z,Q) as a function of
# the fragmentation scale Q, for a few fixed z, from ../files/ff_vs_q_scan.dat
# (generated by directly querying MakeLHAPDFZInterpolator at many Q values --
# see the diagnostic used to produce it). Illustrates why the scale-variation
# uncertainty band is largest at low pD0: Q=SCALE_FACTOR*m_T sits near the
# charm-mass threshold there, where D(z,Q) both jumps on at Q~m_c and varies
# fastest with Q; at high pD0, Q is well above threshold and D(z,Q) is
# nearly flat.

plt.rcParams.update({
    "text.usetex": True,
    "font.family": "serif",
    "font.size": 11,
    "axes.labelsize": 20,
    "axes.titlesize": 20,
    "xtick.labelsize": 18,
    "ytick.labelsize": 18,
    "xtick.direction": "in",
    "ytick.direction": "in",
    "xtick.top": True,
    "ytick.right": True,
    "xtick.major.size": 8,
    "ytick.major.size": 8,
    "xtick.minor.size": 4,
    "ytick.minor.size": 4,
})

mc = 1.5   # charm mass in GeV

data = np.loadtxt("../files/ff_vs_q_scan.dat", comments='#')
Q = data[:, 0]
z_values = [0.3, 0.5, 0.7, 0.9]
colors = ["#9ecae1", "#4292c6", "#08519c", "#08306b"]

plt.figure(figsize=(7.5, 6.0))
for i, z in enumerate(z_values):
    plt.plot(Q, data[:, i + 1], color=colors[i], linewidth=2, label=f"$z={z:g}$")

plt.axvline(mc, color="gray", linestyle=":", linewidth=1)
plt.text(mc * 1.08, 1.55, r"$m_c$", fontsize=16, color="gray")

plt.xscale("log")
plt.xlabel(r"$Q$ [GeV]", labelpad=15)
plt.ylabel(r"$D_{c\to D^0}(z,Q)$", labelpad=15)
plt.title(r"Charm$\to D^0$ fragmentation function vs.\ scale $Q$", pad=15)
plt.legend(loc="upper right", fontsize=15)

plt.figtext(0.5, -0.03,
            r"Below $Q\approx m_c$, $D(z,Q)=0$ (grid's charm-production threshold); "
            r"just above it, $D$ turns on sharply, then flattens at high $Q$.",
            fontsize=9, color="dimgray", ha="center")

plt.tight_layout()
outname = "../plots/ff_vs_q.pdf"
plt.savefig(outname, bbox_inches="tight")
print(f"Saved: {outname}")
