add_library(
    amplitude
    STATIC
    amplitudelib.cpp
    datafile.cpp
    tools.cpp
    interpolation.cpp
)

add_executable(
    D0
    integrand.cpp
    int_exclusive.cpp
    int_diffractive.cpp
    alphas_running.cpp
    gamma_aa.cpp
    fragmentation.cpp
    lhapdf_grid.cpp
    main.cpp
    fourier.c
)

target_link_libraries(
    D0
    PRIVATE
    amplitude
    GSL::gsl
    GSL::gslcblas
    OpenMP::OpenMP_CXX
)

add_executable(
    D0_xpom
    integrand.cpp
    int_exclusive.cpp
    int_diffractive.cpp
    alphas_running.cpp
    gamma_aa.cpp
    fragmentation.cpp
    lhapdf_grid.cpp
    main_xpom.cpp
    fourier.c
)

target_link_libraries(
    D0_xpom
    PRIVATE
    amplitude
    GSL::gsl
    GSL::gslcblas
    OpenMP::OpenMP_CXX
)

add_executable(
    D0_fixedW
    integrand.cpp
    int_exclusive.cpp
    int_diffractive.cpp
    alphas_running.cpp
    gamma_aa.cpp
    fragmentation.cpp
    lhapdf_grid.cpp
    main_fixedW.cpp
    fourier.c
)

target_link_libraries(
    D0_fixedW
    PRIVATE
    amplitude
    GSL::gsl
    GSL::gslcblas
    OpenMP::OpenMP_CXX
)

add_executable(
    D0_fixedW_xpom
    integrand.cpp
    int_exclusive.cpp
    int_diffractive.cpp
    alphas_running.cpp
    gamma_aa.cpp
    fragmentation.cpp
    lhapdf_grid.cpp
    main_fixedW_xpom.cpp
    fourier.c
)

target_link_libraries(
    D0_fixedW_xpom
    PRIVATE
    amplitude
    GSL::gsl
    GSL::gslcblas
    OpenMP::OpenMP_CXX
)
